### ISSUE TITLE
access denied ("java.net.URLPermission" "http://127.0.0.1:7777/status" "GET:Content-Type,User-Agent")

### ISSUE THREAD

**Issue by sattabrotochy** [eggnstone/DartFormatJetbrainsPlugin#103]
Please supply any additional information here, e.g. the source code that caused the error:

```
java.security.AccessControlException: access denied ("java.net.URLPermission" "http://127.0.0.1:7777/status" "GET:Content-Type,User-Agent")
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:485)
	at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:453)
	at java.net.http/jdk.internal.net.http.Exchange.checkPermissions(Exchange.java:639)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsyncImpl(Exchange.java:376)
	at java.net.http/jdk.internal.net.http.Exchange.responseAsync(Exchange.java:372)
	at java.net.http/jdk.internal.net.http.MultiExchange.responseAsyncImpl(MultiExchange.java:408)
	at java.net.http/jdk.internal.net.http.MultiExchange.lambda$responseAsync0$2(MultiExchange.java:341)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
	at java.base/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)

```
Origin: ExternalDartFormat.run/Exception
OS: Windows 11
Plugin version: 2.0.20
External dart_format version: 1.1.20

**Comment by eggnstone** [comment]
Hi.
The plugin uses an external program called dart_format. 
That program is started by the plugin.
They communicate via HTTP on the port 7777.
You can also copy http://127.0.0.1:7777/status into your browser to connect to that service (the IDE must be started) to see the status.
It seems you have some software installed that does not allow inter-process communication or maybe you denied a popup from your IDE requesting that.
Could that be an explanation?

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
