### ISSUE TITLE
External dart_format process is dead.

### ISSUE THREAD

**Issue by Vasew** [eggnstone/DartFormatJetbrainsPlugin#105]
Please supply any additional information here, e.g. the source code that caused the error:

```
DartFormatException(type=Error, source=Local, message=External dart_format process is dead., cause=null, line=null, column=null)
	at dev.eggnstone.plugins.jetbrains.dartformat.DartFormatException$Companion.localError(DartFormatException.kt:20)
	at dev.eggnstone.plugins.jetbrains.dartformat.DartFormatException$Companion.localError$default(DartFormatException.kt:18)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat.run(ExternalDartFormat.kt:247)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat.access$run(ExternalDartFormat.kt:21)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat$run$1.invokeSuspend(ExternalDartFormat.kt
```
Origin: ExternalDartFormat.run/Exception
OS: Mac OS X
Plugin version: 2.0.15
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
