### ISSUE TITLE
Installer for external dart_format process is dead.

### ISSUE THREAD

**Issue by Fiqiefendiahmad** [eggnstone/DartFormatJetbrainsPlugin#114]
Please supply any additional information here, e.g. the source code that caused the error:

```
DartFormatException(type=Error, source=Local, message=Installer for external dart_format process is dead., cause=null, line=null, column=null)
	at dev.eggnstone.plugins.jetbrains.dartformat.DartFormatException$Companion.localError(DartFormatException.kt:20)
	at dev.eggnstone.plugins.jetbrains.dartformat.DartFormatException$Companion.localError$default(DartFormatException.kt:18)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat.tryInstall(ExternalDartFormat.kt:603)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat.access$tryInstall(ExternalDartFormat.kt:27)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat$tryInstall$1.invokeSuspend(ExternalDartFormat.kt)
```
Origin: ExternalDartFormat.run/Exception
OS: Windows 11
Plugin version: 2.0.21
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Does restarting the IDE help?

Otherwise please attach the latest `DartFormatPlugin_...log` from your temp dir.
Use `echo %TEMP%` to find your temp dir.

**Comment by eggnstone** [comment]
It seems that Dart is not reachable via the command line.
Did you install Dart/Flutter?
Did you put it in the PATH variable?

Please see here:           
Linux: https://docs.flutter.dev/get-started/install/linux/android#add-flutter-to-your-path
macOS: https://docs.flutter.dev/get-started/install/macos/mobile-ios#add-flutter-to-your-path
Windows: https://docs.flutter.dev/get-started/install/windows/mobile#update-your-windows-path-variable
