### ISSUE TITLE
Cannot run program "dart_format": error=2, No such file or directory

### ISSUE THREAD

**Issue by YifengDuan** [eggnstone/DartFormatJetbrainsPlugin#14]
Please supply any additional information here, e.g. the source code that caused the error:

```
java.io.IOException: Cannot run program "dart_format": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat$run$process$1.invokeSuspend(ExternalDartFormat.kt:87
```

**Comment by eggnstone** [comment]
Hi.
Did you install the dart_format package from pub.dev?
Just call dart pub global activate dart_format.
Then dart_format on the command line should work. Does it?
Then it should work inside the IDE, too.

**Comment by eggnstone** [comment]
Please reopen if the problem persists
