### ISSUE TITLE
Installer for external dart_format process is dead.

### ISSUE THREAD

**Issue by AguoruJB** [eggnstone/DartFormatJetbrainsPlugin#86]
Please supply any additional information here, e.g. the source code that caused the error:

```
DartFormatException(type=Error, source=Local, message=Installer for external dart_format process is dead., cause=null, line=null, column=null)
	at dev.eggnstone.plugins.jetbrains.dartformat.DartFormatException$Companion.localError(DartFormatException.kt:20)
	at dev.eggnstone.plugins.jetbrains.dartformat.DartFormatException$Companion.localError$default(DartFormatException.kt:18)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat.tryInstall(ExternalDartFormat.kt:608)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat.access$tryInstall(ExternalDartFormat.kt:26)
	at dev.eggnstone.plugins.jetbrains.dartformat.plugin.ExternalDartFormat$tryInstall$1.invokeSuspend(ExternalDartFormat.kt)
```
Origin: ExternalDartFormat.run/Exception
OS: Windows 10
Plugin version: 2.0.17
External dart_format version: <unknown version>

**Comment by eggnstone** [comment]
Please attach the latest DartFormatPlugin....log from %temp%

**Comment by eggnstone** [comment]
Please try the latest version:
https://plugins.jetbrains.com/plugin/21003-dartformat/versions/stable/599098

**Comment by eggnstone** [comment]
Can you try the latest version please?
I am pretty sure that I fixed the issue :)
